exp_name: MAAC-R
result_dir: ../results/MAAC-R
# 第一个cuda device的编号, -1代表cpu
first_device: 0
# cuda device的数量, 使用cpu时无效
gpus: 1
seed: 42
cooperative: 0.3
environment:
  n_uav: 3
  m_targets: 10
  n_protectors: 3
  x_max: 2000 # 地图x轴最大范围
  y_max: 2000 # 地图y轴最大范围
  na: 12  # 离散化动作空间维数

uav:
  dt: 1 # 时间步长
  v_max: 20 # 最大速度
  h_max: 6  # 表示 pi / 6
  dc: 500 # 重复追踪半径惩罚
  dp: 200 #
  alpha: 0.6 
  beta: 0.2
  gamma: 0.2
  omega: 0.5

protector:
  n_protectors: 3
  v_max: 5
  h_max: 6         # 与 UAV 一致的角速度档转弧度
  dt: 0.1
  safe_radius: 200.0  # 与 UAV 进入这个会被惩罚
  knockback: 200.0     # 弹开强度（最大推离距离）
  arm_thickness: 100.0 # 手臂碰撞厚度（判定范围）

target:
  v_max: 5
  h_max: 6  # 表示 pi / 6
  capture_radius: 120.0  # 目标捕获半径（小于此半径会被捕获）

actor_critic:
  buffer_size: 1000000
  sample_size: 0  # 表示每次采样的大小为每个epoch的step数
  actor_lr: 1e-4
  critic_lr: 1e-4
  hidden_dim: 256
  gamma: 0.95

pmi:
  hidden_dim: 128
  b2_size: 3000
  batch_size: 128